### ISSUE TITLE
求助作者：拓扑诱饵集和构象诱饵集是否可以只选一个？

### ISSUE THREAD

**Issue by bigsmartguy** [5AGE-zhang/TocoDecoy#1]
作者你好，我在完成一份基于配体的虚拟筛选工作，需要建立小分子数据集，活性样本已从文献中得到，非活性样本准备使用您开发的TocoDecoy来构建。
现在问题是我的靶点蛋白有两个活性结合位点，而且文献中报道的活性分子也没有指明具体结合到哪一个口袋。

所以我想问一下我在使用TocoDecoy构建负样本时，可不可以只要拓扑诱饵集(TD)，而不要构象诱饵集呢？

**Comment by BlANK-0615** [comment]
> 作者你好，我在完成一份基于配体的虚拟筛选工作，需要建立小分子数据集，活性样本已从文献中得到，非活性样本准备使用您开发的TocoDecoy来构建。 现在问题是我的靶点蛋白有两个活性结合位点，而且文献中报道的活性分子也没有指明具体结合到哪一个口袋。
> 
> 所以我想问一下我在使用TocoDecoy构建负样本时，可不可以只要拓扑诱饵集(TD)，而不要构象诱饵集呢？

您好，请问您使用TocoDecoy成功生成了诱饵吗？我目前也需要产生decoys来训练虚筛模型，如果能交流一下就太好了

**Comment by bigsmartguy** [comment]
你好，我后来换了方法，并没有使用这个来产生诱饵集。而是使用了DUD-E在线网站生成的诱饵集


| |
lshaohui12138
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年5月22日 00:30 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [5AGE-zhang/TocoDecoy] 求助作者：拓扑诱饵集和构象诱饵集是否可以只选一个？ (Issue #1) |

作者你好，我在完成一份基于配体的虚拟筛选工作，需要建立小分子数据集，活性样本已从文献中得到，非活性样本准备使用您开发的TocoDecoy来构建。 现在问题是我的靶点蛋白有两个活性结合位点，而且文献中报道的活性分子也没有指明具体结合到哪一个口袋。

所以我想问一下我在使用TocoDecoy构建负样本时，可不可以只要拓扑诱饵集(TD)，而不要构象诱饵集呢？

您好，请问您使用TocoDecoy成功生成了诱饵吗？我目前也需要产生decoys来训练虚筛模型，如果能交流一下就太好了

**Comment by BlANK-0615** [comment]
> 你好，我后来换了方法，并没有使用这个来产生诱饵集。而是使用了DUD-E在线网站生成的诱饵集 | | lshaohui12138 | | ***@***.*** | ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2023年5月22日 00:30 | | 收件人 | ***@***.***> | | 抄送人 | ***@***.***> , ***@***.***> | | 主题 | Re: [5AGE-zhang/TocoDecoy] 求助作者：拓扑诱饵集和构象诱饵集是否可以只选一个？ (Issue #1) | 作者你好，我在完成一份基于配体的虚拟筛选工作，需要建立小分子数据集，活性样本已从文献中得到，非活性样本准备使用您开发的TocoDecoy来构建。 现在问题是我的靶点蛋白有两个活性结合位点，而且文献中报道的活性分子也没有指明具体结合到哪一个口袋。 所以我想问一下我在使用TocoDecoy构建负样本时，可不可以只要拓扑诱饵集(TD)，而不要构象诱饵集呢？ 您好，请问您使用TocoDecoy成功生成了诱饵吗？我目前也需要产生decoys来训练虚筛模型，如果能交流一下就太好了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

非常感谢您的回复，最后还想问一下Tocodecoy生成诱饵的难度是否太大了？以及如果可以的话您方便给一个邮箱用于后续沟通吗？

**Comment by bigsmartguy** [comment]
好的，我的邮箱是lshaohui12138  @***.*** 加com(网易的163邮箱）
GitHub上好像不让直接写邮箱地址，所以我分开写了，见谅~


| |
lshaohui12138
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年5月22日 16:16 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [5AGE-zhang/TocoDecoy] 求助作者：拓扑诱饵集和构象诱饵集是否可以只选一个？ (Issue #1) |

你好，我后来换了方法，并没有使用这个来产生诱饵集。而是使用了DUD-E在线网站生成的诱饵集 | | lshaohui12138 | | @.*** | ---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2023年5月22日 00:30 | | 收件人 | @.> | | 抄送人 | @.> , @.> | | 主题 | Re: [5AGE-zhang/TocoDecoy] 求助作者：拓扑诱饵集和构象诱饵集是否可以只选一个？ (Issue #1) | 作者你好，我在完成一份基于配体的虚拟筛选工作，需要建立小分子数据集，活性样本已从文献中得到，非活性样本准备使用您开发的TocoDecoy来构建。 现在问题是我的靶点蛋白有两个活性结合位点，而且文献中报道的活性分子也没有指明具体结合到哪一个口袋。 所以我想问一下我在使用TocoDecoy构建负样本时，可不可以只要拓扑诱饵集(TD)，而不要构象诱饵集呢？ 您好，请问您使用TocoDecoy成功生成了诱饵吗？我目前也需要产生decoys来训练虚筛模型，如果能交流一下就太好了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

非常感谢您的回复，最后还想问一下Tocodecoy生成诱饵的难度是否太大了？以及如果可以的话您方便给一个邮箱用于后续沟通吗？

**Comment by BlANK-0615** [comment]
> 好的，我的邮箱是lshaohui12138 @***.*** 加com(网易的163邮箱） GitHub上好像不让直接写邮箱地址，所以我分开写了，见谅~ | | lshaohui12138 | | ***@***.*** | ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2023年5月22日 16:16 | | 收件人 | ***@***.***> | | 抄送人 | ***@***.***> , ***@***.***> | | 主题 | Re: [5AGE-zhang/TocoDecoy] 求助作者：拓扑诱饵集和构象诱饵集是否可以只选一个？ (Issue #1) | 你好，我后来换了方法，并没有使用这个来产生诱饵集。而是使用了DUD-E在线网站生成的诱饵集 | | lshaohui12138 | | @.*** | ---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2023年5月22日 00:30 | | 收件人 | @.> | | 抄送人 | @.> , @.> | | 主题 | Re: [5AGE-zhang/TocoDecoy] 求助作者：拓扑诱饵集和构象诱饵集是否可以只选一个？ (Issue #1) | 作者你好，我在完成一份基于配体的虚拟筛选工作，需要建立小分子数据集，活性样本已从文献中得到，非活性样本准备使用您开发的TocoDecoy来构建。 现在问题是我的靶点蛋白有两个活性结合位点，而且文献中报道的活性分子也没有指明具体结合到哪一个口袋。 所以我想问一下我在使用TocoDecoy构建负样本时，可不可以只要拓扑诱饵集(TD)，而不要构象诱饵集呢？ 您好，请问您使用TocoDecoy成功生成了诱饵吗？我目前也需要产生decoys来训练虚筛模型，如果能交流一下就太好了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***> 非常感谢您的回复，最后还想问一下Tocodecoy生成诱饵的难度是否太大了？以及如果可以的话您方便给一个邮箱用于后续沟通吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

非常感谢，已经邮件联系您了：）

**Comment by 5AGE-zhang** [comment]
> 作者你好，我在完成一份基于配体的虚拟筛选工作，需要建立小分子数据集，活性样本已从文献中得到，非活性样本准备使用您开发的TocoDecoy来构建。 现在问题是我的靶点蛋白有两个活性结合位点，而且文献中报道的活性分子也没有指明具体结合到哪一个口袋。
> 
> 所以我想问一下我在使用TocoDecoy构建负样本时，可不可以只要拓扑诱饵集(TD)，而不要构象诱饵集呢？

不常看Github，现在才看到，抱歉。
只用拓扑诱饵集(TD)的话，就不是TocoDecoy的方法了，更类似于DUD-E的方法，会导致因果偏差的出现，因此不建议在表征的时候加入配体的拓扑信息。
另外，我们开发了一个在线数据库（ http://cadd.zju.edu.cn/tocodecoy/ ）
数据库收集并整合了来自DUD-E,DEKOIS和LIT-PCBA中的活性分子，采用TocoDecoy的方法构建了155个不同靶标的数据集，同时也提供了TD数据集在线生成的功能。
大家需要的话，可以访问使用。
